##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-sensors-applet
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - gettext
    - git
    - libcairo2-dev
    - libglib2.0-dev
    - libnotify-dev
    - libsensors4-dev
    - libtool
    - libxml-parser-perl
    - libxnvctrl-dev
    - make
    - yelp-tools

    #required for cafe-panel
    - gir1.2-freedesktop
    - gobject-introspection
    - gtk-doc-tools
    - libatk1.0-dev
    - libdconf-dev
    - libgirepository1.0-dev
    - libice-dev
    - libpango1.0-dev
    - librsvg2-dev
    - libsm-dev
    - libsoup2.4-dev
    - libx11-dev
    - libxau-dev
    - libxrandr-dev
    - lsb-release
    - meson

    #required for cafe-desktop
    - intltool
    - iso-codes
    - libstartup-notification0-dev
    - libxml2-dev

before_scripts:
  - ./html-cppcheck
  - ./debrepo-install 'libctk-3-dev gir1.2-ctk-3.0 libctk-3-common libctk-3-0 libctk-3-doc'
  - ./install-from-git https://github.com/cafe-desktop/libvnck master meson
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master
  - ./install-from-git https://github.com/cafe-desktop/cafe-desktop master
  - ./install-from-git https://github.com/cafe-desktop/cafe-menus master
  - ./install-from-git https://github.com/cafe-desktop/libcafeweather master
  - ./install-from-git https://github.com/cafe-desktop/cafe-panel master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi
