##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-sensors-applet
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - gettext
    - git
    - libcairo2-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-panel-applet-dev
    - libnotify-dev
    - libsensors4-dev
    - libtool
    - libxml-parser-perl
    - libxnvctrl-dev
    - make
    - yelp-tools

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/mate-desktop/mate-common master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi
